### ISSUE TITLE
No loot shown for Grotesque Gaurdians

### ISSUE THREAD

**Issue by Isolol** [Mrnice98/BossingInfo#13]
I haven't done Grotesque Guardians in a while so not sure if this is a recent development, but I noticed that the plugin isn't tracking loot for them. Upon looking at the logs for the client, I see this error:

2023-08-14 20:25:20 EDT [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
         java.lang.NullPointerException: null
	at com.killsperhour.KphPanel.lootGrid(KphPanel.java:376)
	at com.killsperhour.KphPanel.lambda$updateLootGrid$3(KphPanel.java:366)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Edit: Apologies, I see the other issue now.

**Comment by Isolol** [comment]
Opened before I saw the other open issue #9
